### ISSUE TITLE
i18n not responding

### ISSUE THREAD

**Issue by kimd20** [SAP-samples/teched2021-DEV160#7]
Hello, I have been following the exercise steps, but it seems like adding ?sap-ui-language=de at the end of the app URL doesn't cause localization to occur.

I have changed the i18n model in manifest.json file, as shown below. (I have added kr in the supported Locales, as I was trying out additional language. I have also created i18n_kr.properties under webapp/i18n folder)
![Snag_475de5](https://user-images.githubusercontent.com/42676420/142959915-be1e5e7a-7231-4e11-b826-14265f223496.png)

In the node Debug Console I have consistently been getting this error message as well. Could this be the cause of the issue? If so, would there be a possible solution to this issue?

Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
    at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:131:17)

Thank You!

Phillip

**Comment by martinhaeuser** [comment]
Hello Phillip,

the configuration you added seems to be fine. Please ensure when you are testing with the URL parameter to add it before the hash, for example:

/flpSandbox.html?**sap-ui-language=kr**#keepcoolsensormanager-display

Note: You can also try to change the language configuration of your browser to verify the localization (which is closer to the real use case)

Kindly retest and revert in case you still encounter issues with the localization!

Thanks & Regards
Martin
